language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.pip-cache/
install: pip install -r requirements.txt --download-cache $HOME/.pip-cache
script: nosetests
